package Interfaz;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.JTableHeader;
import Consultas.Inventario2;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Inventario extends javax.swing.JInternalFrame {
   Inventario2 inv = new Inventario2();
   RedimensionarImg redi = new RedimensionarImg();
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpciones = new javax.swing.JPanel();
        btnAgregarProd = new javax.swing.JButton();
        btnModificarProd = new javax.swing.JButton();
        btnEliminarProd = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        panelProd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInv = new javax.swing.JTable();
        panelDet = new javax.swing.JScrollPane();
        panelDetalles = new javax.swing.JPanel();
        lblNumProd = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblExis = new javax.swing.JLabel();
        lblDescrip = new javax.swing.JLabel();
        txtNumProd = new javax.swing.JTextField();
        txtExis = new javax.swing.JTextField();
        txtDescrip = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        cbxTipo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(144, 144, 144));
        setBorder(null);
        setName("jInternalInventario"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panelOpciones.setBackground(new java.awt.Color(61, 71, 90));
        panelOpciones.setPreferredSize(new java.awt.Dimension(741, 50));

        btnAgregarProd.setBackground(new java.awt.Color(54, 68, 97));
        btnAgregarProd.setToolTipText("Agregar Cliente");
        btnAgregarProd.setBorder(null);
        btnAgregarProd.setBorderPainted(false);
        btnAgregarProd.setContentAreaFilled(false);
        btnAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProd.setFocusPainted(false);
        btnAgregarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProdMouseExited(evt);
            }
        });
        btnAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProdActionPerformed(evt);
            }
        });

        btnModificarProd.setBackground(new java.awt.Color(54, 68, 97));
        btnModificarProd.setToolTipText("Modificar Datos del Cliente");
        btnModificarProd.setAlignmentY(0.2F);
        btnModificarProd.setBorder(null);
        btnModificarProd.setBorderPainted(false);
        btnModificarProd.setContentAreaFilled(false);
        btnModificarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarProd.setFocusPainted(false);
        btnModificarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarProdMouseExited(evt);
            }
        });
        btnModificarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProdActionPerformed(evt);
            }
        });

        btnEliminarProd.setBackground(new java.awt.Color(54, 68, 97));
        btnEliminarProd.setToolTipText("Eliminar Cliente");
        btnEliminarProd.setAlignmentY(0.2F);
        btnEliminarProd.setBorder(null);
        btnEliminarProd.setBorderPainted(false);
        btnEliminarProd.setContentAreaFilled(false);
        btnEliminarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarProd.setFocusPainted(false);
        btnEliminarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarProdMouseExited(evt);
            }
        });
        btnEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProdActionPerformed(evt);
            }
        });

        btnCheck.setAlignmentY(0.2F);
        btnCheck.setBorder(null);
        btnCheck.setBorderPainted(false);
        btnCheck.setContentAreaFilled(false);
        btnCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheck.setFocusPainted(false);
        btnCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckMouseExited(evt);
            }
        });
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(panelOpciones, java.awt.BorderLayout.NORTH);

        panelContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(102, 102, 102)));
        panelContenido.setOpaque(false);
        panelContenido.setLayout(new java.awt.GridLayout(2, 1));

        panelProd.setBackground(new java.awt.Color(71, 80, 98));

        tblInv.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblInv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblInv.setRowHeight(20);
        tblInv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInv);

        javax.swing.GroupLayout panelProdLayout = new javax.swing.GroupLayout(panelProd);
        panelProd.setLayout(panelProdLayout);
        panelProdLayout.setHorizontalGroup(
            panelProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        panelProdLayout.setVerticalGroup(
            panelProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );

        panelContenido.add(panelProd);

        panelDet.setBorder(null);

        panelDetalles.setBackground(new java.awt.Color(222, 222, 222));

        lblNumProd.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lblNumProd.setText("No. Producto:");

        lblTipo.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lblTipo.setText("Tipo:");

        lblExis.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lblExis.setText("Existencia:");

        lblDescrip.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lblDescrip.setText("Descripción:");

        txtNumProd.setEditable(false);
        txtNumProd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNumProd.setForeground(new java.awt.Color(52, 52, 52));

        txtExis.setEditable(false);
        txtExis.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtExis.setForeground(new java.awt.Color(52, 52, 52));

        txtDescrip.setEditable(false);
        txtDescrip.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDescrip.setForeground(new java.awt.Color(52, 52, 52));

        cbxTipo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumProd)
                    .addComponent(lblTipo)
                    .addComponent(lblDescrip))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumProd)
                            .addComponent(cbxTipo, 0, 226, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesLayout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetallesLayout.createSequentialGroup()
                                        .addComponent(lblExis)
                                        .addGap(48, 48, 48))
                                    .addComponent(txtExis)))
                            .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(304, 304, 304))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(txtDescrip)
                        .addGap(484, 484, 484))))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumProd)
                    .addComponent(txtNumProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblExis)
                            .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTipo)
                                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescrip)
                                .addComponent(txtDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesLayout.createSequentialGroup()
                                .addComponent(txtExis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelDet.setViewportView(panelDetalles);

        panelContenido.add(panelDet);

        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        JTableHeader th; 
        th = tblInv.getTableHeader(); 
        th.setFont(new java.awt.Font("Eras Medium ITC", 1, 15)); 
        tblInv.setModel(inv.verInventario());
        ImageIcon img[] = new ImageIcon[9];
        img[0] = new ImageIcon(getClass().getResource("/Imagenes/14.icono_addCliente.png"));
        img[1] = new ImageIcon(getClass().getResource("/Imagenes/15.modificar_cliente.png"));
        img[2] = new ImageIcon(getClass().getResource("/Imagenes/16.eliminar_cliente.png"));
        img[3] = new ImageIcon(getClass().getResource("/Imagenes/17.check.png"));
        img[4] = new ImageIcon(getClass().getResource("/Imagenes/17.check1.png"));
        img[5] = new ImageIcon(getClass().getResource("/Imagenes/18.cancelar.png"));
        redi.escalarImagen(btnAgregarProd, img[0]);
        redi.escalarImagen(btnModificarProd, img[1]);
        redi.escalarImagen(btnEliminarProd, img[2]);
        redi.escalarImagen(btnCheck, img[3]);
        //redi.escalarImagen(btnCheck1, img[4]);
        redi.escalarImagen(btnCancelar, img[5]);
        this.btnCheck.setVisible(false);
        //this.btnCheck1.setVisible(false);
        this.btnCancelar.setVisible(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAgregarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProdMouseEntered
        redi.escalarImagen2(btnAgregarProd, new ImageIcon(getClass().getResource("/Imagenes/14.icono_addCliente.png")));
    }//GEN-LAST:event_btnAgregarProdMouseEntered

    private void btnAgregarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProdMouseExited
        redi.escalarImagen(btnAgregarProd, new ImageIcon(getClass().getResource("/Imagenes/14.icono_addCliente.png")));
    }//GEN-LAST:event_btnAgregarProdMouseExited

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        int idSig = inv.ultimoID()+1;
        limpiar();
        txtNumProd.setText(Integer.toString(idSig));
        this.btnCheck.setVisible(true);
        this.btnCancelar.setVisible(true);
        this.btnAgregarProd.setVisible(false);
        this.btnModificarProd.setVisible(false);
        this.btnEliminarProd.setVisible(false);
        txtNumProd.setEditable(true);
        this.cbxTipo.addItem("Bote Plástico");
        this.cbxTipo.addItem("Bote Costal");
        txtExis.setEditable(true);
        txtDescrip.setEditable(true);

    }//GEN-LAST:event_btnAgregarProdActionPerformed
    private void limpiar(){
        txtNumProd.setText("");
        cbxTipo.removeAllItems();
        txtExis.setText("");
        txtDescrip.setText("");
    }
    private void btnModificarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarProdMouseEntered
        redi.escalarImagen2(btnModificarProd, new ImageIcon(getClass().getResource("/Imagenes/15.modificar_cliente.png")));
    }//GEN-LAST:event_btnModificarProdMouseEntered

    private void btnModificarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarProdMouseExited
        redi.escalarImagen(btnModificarProd, new ImageIcon(getClass().getResource("/Imagenes/15.modificar_cliente.png")));
    }//GEN-LAST:event_btnModificarProdMouseExited

    private void btnModificarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProdActionPerformed
        this.btnCheck.setVisible(true);
        this.btnCancelar.setVisible(true);
    }//GEN-LAST:event_btnModificarProdActionPerformed

    private void btnEliminarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProdMouseEntered
        redi.escalarImagen2(btnEliminarProd, new ImageIcon(getClass().getResource("/Imagenes/16.eliminar_cliente.png")));
    }//GEN-LAST:event_btnEliminarProdMouseEntered

    private void btnEliminarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProdMouseExited
        redi.escalarImagen(btnEliminarProd, new ImageIcon(getClass().getResource("/Imagenes/16.eliminar_cliente.png")));
    }//GEN-LAST:event_btnEliminarProdMouseExited

    private void btnEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdActionPerformed
        int fila = tblInv.getSelectedRow();
        String valor = tblInv.getValueAt(fila, 0).toString();
        if(fila>=0){
            //Eliminar producto
        }
    }//GEN-LAST:event_btnEliminarProdActionPerformed

    private void btnCheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckMouseEntered
        redi.escalarImagen2(btnCheck, new ImageIcon(getClass().getResource("/Imagenes/17.check.png")));
    }//GEN-LAST:event_btnCheckMouseEntered

    private void btnCheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckMouseExited
        redi.escalarImagen(btnCheck, new ImageIcon(getClass().getResource("/Imagenes/17.check.png")));
    }//GEN-LAST:event_btnCheckMouseExited

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Modificó Datos\n¿Desea continuar?", "Cerrar", JOptionPane.YES_NO_OPTION, 0,
            new ImageIcon(getClass().getResource("/Imagenes/modificar.png"))) == JOptionPane.YES_OPTION) {
        //Actualiza los datos con procedimiento almacenado
        this.btnAgregarProd.setVisible(true);
        this.btnModificarProd.setVisible(true);
        this.btnEliminarProd.setVisible(true);
        if (("".equals(txtNumProd.getText()))||("".equals(txtDescrip.getText()))||("".equals(cbxTipo.getSelectedItem()))||
            ("".equals(txtExis.getText()))){
            JOptionPane.showMessageDialog(null, "Hacen falta datos, por favor ingreselos");
        }else{
            //Agregar producto
            inv.agregarInv(this.txtNumProd.getText(), (String)cbxTipo.getSelectedItem(), this.txtDescrip.getText(), this.txtExis.getText());
            tblInv.setModel(inv.verInventario());
        }
        this.txtNumProd.setEditable(false);
        this.txtDescrip.setEditable(false);
        this.cbxTipo.removeAllItems();
        this.txtExis.setEditable(false);
        this.btnCheck.setVisible(false);
        this.btnCancelar.setVisible(false);

        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        redi.escalarImagen2(btnCancelar, new ImageIcon(getClass().getResource("/Imagenes/18.cancelar.png")));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        redi.escalarImagen(btnCancelar, new ImageIcon(getClass().getResource("/Imagenes/18.cancelar.png")));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        if (JOptionPane.showConfirmDialog(this, "¿Desea cancelar los cambios?", "Cerrar", JOptionPane.YES_NO_OPTION, 0,
            new ImageIcon(getClass().getResource("/Imagenes/modificar.png"))) == JOptionPane.YES_OPTION) {
            //Cancela los cambios
            this.btnAgregarProd.setVisible(true);
            this.btnModificarProd.setVisible(true);
            this.btnEliminarProd.setVisible(true);
            this.txtNumProd.setEditable(false);
            this.txtDescrip.setEditable(false);
            this.cbxTipo.removeAllItems();
            this.txtExis.setEditable(false);
            this.btnCheck.setVisible(false);
            this.btnCancelar.setVisible(false);
            limpiar();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblInvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvMouseClicked
        if(evt.getClickCount()==2){//Si se hace doble click
            mostrarInv();
        }
    }//GEN-LAST:event_tblInvMouseClicked

    private void mostrarInv(){
        int filaS = this.tblInv.getSelectedRow();
        this.cbxTipo.removeAllItems();
        if(filaS>=0){
            Object datos[]; 
            datos = new Object[4]; 
            for(int i=0; i<4; i++){
                datos[i] = tblInv.getValueAt(filaS, i);
            }
            int nProd = (int) datos[0];
            int exis = (int) datos[3];
            this.txtNumProd.setText(Integer.toString(nProd));
            this.cbxTipo.addItem((String) datos[1]);
            this.txtDescrip.setText((String) datos[2]);
            this.txtExis.setText(Integer.toString(exis));           
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnEliminarProd;
    private javax.swing.JButton btnModificarProd;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescrip;
    private javax.swing.JLabel lblExis;
    private javax.swing.JLabel lblNumProd;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JScrollPane panelDet;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelProd;
    private javax.swing.JTable tblInv;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtExis;
    private javax.swing.JTextField txtNumProd;
    // End of variables declaration//GEN-END:variables
}
