package Interfaz;

import Consultas.Cliente;
import Consultas.Pagos;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.JTableHeader;


public class Pago extends javax.swing.JInternalFrame {
    private String serie, numero;
    Cliente cl = new Cliente();
    Pagos pg = new Pagos();
    Date sistemaFech2 = new Date();
    SimpleDateFormat formato2 = new SimpleDateFormat("MMMM");
    String MesCorriente = formato2.format(sistemaFech2).toUpperCase();
    //Arreglo que almacena los meses a pagar
    String[] mesesPago = new String [12];
    public Pago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMeses = new javax.swing.JPopupMenu();
        cbxEnero = new javax.swing.JCheckBoxMenuItem();
        cbxFebrero = new javax.swing.JCheckBoxMenuItem();
        cbxMarzo = new javax.swing.JCheckBoxMenuItem();
        cbxAbril = new javax.swing.JCheckBoxMenuItem();
        cbxMayo = new javax.swing.JCheckBoxMenuItem();
        cbxJunio = new javax.swing.JCheckBoxMenuItem();
        cbxJulio = new javax.swing.JCheckBoxMenuItem();
        cbxAgosto = new javax.swing.JCheckBoxMenuItem();
        cbxSeptiembre = new javax.swing.JCheckBoxMenuItem();
        cbxOctubre = new javax.swing.JCheckBoxMenuItem();
        cbxNoviembre = new javax.swing.JCheckBoxMenuItem();
        cbxDiciembre = new javax.swing.JCheckBoxMenuItem();
        panelContenido = new javax.swing.JPanel();
        panelPrin = new javax.swing.JPanel();
        panelCliente = new javax.swing.JLayeredPane();
        panelBuscarCliente = new javax.swing.JPanel();
        rbDpi = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        txtBuscarCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscar = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        rbApellido = new javax.swing.JRadioButton();
        panelVerCliente = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        lblDpi = new javax.swing.JLabel();
        txtDpi = new javax.swing.JTextField();
        lblMunicipio = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        lblAldea = new javax.swing.JLabel();
        txtAldea = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lblCaserio = new javax.swing.JLabel();
        txtCaserio = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        panelDatos = new javax.swing.JPanel();
        panelFechaEm = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        panelBoleta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNumBoleta = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        panelVerConcepto = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        Monto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        rbMesCorriente = new javax.swing.JRadioButton();
        rbMesesDeuda = new javax.swing.JRadioButton();
        rbVariosMeses = new javax.swing.JRadioButton();
        lblMes = new javax.swing.JLabel();
        btnVerMeses = new javax.swing.JButton();
        cbxMeses = new javax.swing.JComboBox<>();
        cbxConcepto = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jButton1 = new javax.swing.JButton();
        panelDetalles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblComprobante = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));

        cbxEnero.setText("ENERO");
        cbxEnero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEneroItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxEnero);

        cbxFebrero.setText("FEBRERO");
        cbxFebrero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFebreroItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxFebrero);

        cbxMarzo.setText("MARZO");
        cbxMarzo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMarzoItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxMarzo);

        cbxAbril.setText("ABRIL");
        cbxAbril.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAbrilItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxAbril);

        cbxMayo.setText("MAYO");
        cbxMayo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMayoItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxMayo);

        cbxJunio.setText("JUNIO");
        cbxJunio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxJunioItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxJunio);

        cbxJulio.setText("JULIO");
        cbxJulio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxJulioItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxJulio);

        cbxAgosto.setText("AGOSTO");
        cbxAgosto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAgostoItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxAgosto);

        cbxSeptiembre.setText("SEPTIEMBRE");
        cbxSeptiembre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSeptiembreItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxSeptiembre);

        cbxOctubre.setText("OCTUBRE");
        cbxOctubre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxOctubreItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxOctubre);

        cbxNoviembre.setText("NOVIEMBRE");
        cbxNoviembre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNoviembreItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxNoviembre);

        cbxDiciembre.setText("DICIEMBRE");
        cbxDiciembre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDiciembreItemStateChanged(evt);
            }
        });
        popupMeses.add(cbxDiciembre);

        setBackground(new java.awt.Color(144, 144, 144));
        setBorder(null);
        setName("jInternalPago"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panelContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(102, 102, 102)));
        panelContenido.setOpaque(false);

        panelPrin.setOpaque(false);
        panelPrin.setLayout(new java.awt.GridLayout(2, 2, 2, 2));

        panelCliente.setBackground(new java.awt.Color(194, 194, 194));
        panelCliente.setOpaque(true);

        panelBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelBuscarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "BUSCAR CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        panelBuscarCliente.setOpaque(false);

        rbDpi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbDpi.setText("DPI");
        rbDpi.setToolTipText("Buscar Cliente por DPI");
        rbDpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDpiMouseClicked(evt);
            }
        });

        rbNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNombre.setText("Nombre");
        rbNombre.setToolTipText("Buscar Cliente por Nombre");
        rbNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNombreMouseClicked(evt);
            }
        });

        txtBuscarCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyReleased(evt);
            }
        });

        tablaBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3"
            }
        ));
        tablaBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBuscar);

        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Ingresar el Cliente");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        rbApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbApellido.setText("Apellido");
        rbApellido.setToolTipText("Buscar Cliente por Apellido");
        rbApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbApellidoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarClienteLayout = new javax.swing.GroupLayout(panelBuscarCliente);
        panelBuscarCliente.setLayout(panelBuscarClienteLayout);
        panelBuscarClienteLayout.setHorizontalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(rbDpi)
                        .addGap(18, 18, 18)
                        .addComponent(rbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        panelBuscarClienteLayout.setVerticalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDpi)
                    .addComponent(rbNombre)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar)
                    .addComponent(rbApellido))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelVerCliente.setBackground(new java.awt.Color(194, 194, 194));
        panelVerCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        lblNombres.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblNombres.setText("Nombres");

        txtNombres.setEditable(false);
        txtNombres.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(52, 52, 52));

        lblApellidos.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblApellidos.setText("Apellidos");

        txtApellidos.setEditable(false);
        txtApellidos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApellidos.setForeground(java.awt.Color.darkGray);

        lblDpi.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblDpi.setText("DPI");

        txtDpi.setEditable(false);
        txtDpi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDpi.setForeground(java.awt.Color.darkGray);

        lblMunicipio.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblMunicipio.setText("Municipio");

        txtMunicipio.setEditable(false);
        txtMunicipio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMunicipio.setForeground(java.awt.Color.darkGray);

        lblAldea.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblAldea.setText("Aldea");

        txtAldea.setEditable(false);
        txtAldea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAldea.setForeground(java.awt.Color.darkGray);

        lblDireccion.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblDireccion.setText("Dirección");

        txtDireccion.setEditable(false);
        txtDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDireccion.setForeground(java.awt.Color.darkGray);

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setToolTipText("Buscar Clientes");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblCaserio.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblCaserio.setText("Caserío");

        txtCaserio.setEditable(false);
        txtCaserio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelVerClienteLayout = new javax.swing.GroupLayout(panelVerCliente);
        panelVerCliente.setLayout(panelVerClienteLayout);
        panelVerClienteLayout.setHorizontalGroup(
            panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                        .addComponent(btnBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                        .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombres))
                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAldea, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDireccion))
                                .addGap(17, 17, 17)
                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtDpi)
                                    .addComponent(txtAldea, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblCaserio)
                                .addGap(52, 52, 52)
                                .addComponent(txtCaserio)
                                .addGap(42, 42, 42))
                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellidos)
                                    .addComponent(lblMunicipio))
                                .addGap(31, 31, 31)
                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtMunicipio))
                                .addGap(43, 43, 43))))))
        );
        panelVerClienteLayout.setVerticalGroup(
            panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAldea))
                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                        .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                                                        .addGap(3, 3, 3)
                                                        .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDpi))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)))
                                .addGap(6, 6, 6)
                                .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtAldea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelVerClienteLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(panelVerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCaserio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCaserio)))))
                            .addGroup(panelVerClienteLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        panelCliente.setLayer(panelBuscarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCliente.setLayer(panelVerCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrin.add(panelCliente);

        panelDatos.setBackground(new java.awt.Color(194, 194, 194));
        panelDatos.setMinimumSize(new java.awt.Dimension(0, 0));

        panelFechaEm.setBackground(new java.awt.Color(255, 255, 255));
        panelFechaEm.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "FECHA DE EMISIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N
        panelFechaEm.setMinimumSize(new java.awt.Dimension(0, 0));
        panelFechaEm.setOpaque(false);

        lblFecha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelFechaEmLayout = new javax.swing.GroupLayout(panelFechaEm);
        panelFechaEm.setLayout(panelFechaEmLayout);
        panelFechaEmLayout.setHorizontalGroup(
            panelFechaEmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaEmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFechaEmLayout.setVerticalGroup(
            panelFechaEmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaEmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBoleta.setBackground(new java.awt.Color(255, 255, 255));
        panelBoleta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "BOLETA", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N
        panelBoleta.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(98, 174, 174));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No.");
        jLabel1.setOpaque(true);

        lblNumBoleta.setBackground(new java.awt.Color(179, 179, 179));
        lblNumBoleta.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblNumBoleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumBoleta.setText("000001");
        lblNumBoleta.setOpaque(true);

        javax.swing.GroupLayout panelBoletaLayout = new javax.swing.GroupLayout(panelBoleta);
        panelBoleta.setLayout(panelBoletaLayout);
        panelBoletaLayout.setHorizontalGroup(
            panelBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(panelBoletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBoletaLayout.setVerticalGroup(
            panelBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoletaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(filler9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFechaEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(panelBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17)
                                .addComponent(panelFechaEm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(filler9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addComponent(filler8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        panelPrin.add(panelDatos);

        panelVerConcepto.setBackground(new java.awt.Color(194, 194, 194));
        panelVerConcepto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "DATOS DE CONCEPTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N
        panelVerConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVerConceptoMouseClicked(evt);
            }
        });

        lblDescripcion.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblDescripcion.setText("Descripción");

        Monto.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        Monto.setText("Monto");

        txtMonto.setEditable(false);
        txtMonto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMontoMouseClicked(evt);
            }
        });

        rbMesCorriente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rbMesCorriente.setText("Mes Corriente");
        rbMesCorriente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMesCorrienteMouseClicked(evt);
            }
        });

        rbMesesDeuda.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rbMesesDeuda.setText("Meses en deuda");
        rbMesesDeuda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbMesesDeudaItemStateChanged(evt);
            }
        });
        rbMesesDeuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMesesDeudaMouseClicked(evt);
            }
        });

        rbVariosMeses.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rbVariosMeses.setText("Varios Meses");
        rbVariosMeses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbVariosMesesItemStateChanged(evt);
            }
        });
        rbVariosMeses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbVariosMesesMouseClicked(evt);
            }
        });

        lblMes.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblMes.setText("Mes");

        btnVerMeses.setText("Ver");
        btnVerMeses.setToolTipText("Ver Meses");
        btnVerMeses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMesesMouseClicked(evt);
            }
        });

        cbxMeses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cbxConcepto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxConcepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MENSUALIDAD", "INSCRIPCIÓN" }));
        cbxConcepto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxConceptoItemStateChanged(evt);
            }
        });

        filler2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filler2MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jButton1.setText("Registrar Pago");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVerConceptoLayout = new javax.swing.GroupLayout(panelVerConcepto);
        panelVerConcepto.setLayout(panelVerConceptoLayout);
        panelVerConceptoLayout.setHorizontalGroup(
            panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelVerConceptoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(rbMesCorriente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVariosMeses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMesesDeuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filler4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelVerConceptoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Monto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMes, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(10, 10, 10)
                .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerConceptoLayout.createSequentialGroup()
                        .addComponent(cbxConcepto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelVerConceptoLayout.createSequentialGroup()
                        .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVerConceptoLayout.createSequentialGroup()
                                .addComponent(txtMonto)
                                .addGap(38, 38, 38)
                                .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelVerConceptoLayout.createSequentialGroup()
                                .addComponent(cbxMeses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(btnVerMeses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelVerConceptoLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelVerConceptoLayout.setVerticalGroup(
            panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerConceptoLayout.createSequentialGroup()
                .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVerConceptoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVerConceptoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMesCorriente)
                            .addComponent(rbMesesDeuda)
                            .addComponent(rbVariosMeses)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerConceptoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMes))
                .addGap(7, 7, 7)
                .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelVerConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Monto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        panelPrin.add(panelVerConcepto);

        panelDetalles.setBackground(new java.awt.Color(194, 194, 194));
        panelDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "COMPROBANTE DE PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        tblComprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblComprobante);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(31, 187, 31));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total");

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(filler7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(24, 24, 24))
        );

        panelPrin.add(panelDetalles);

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrin, javax.swing.GroupLayout.PREFERRED_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrin, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        //Fehca del sistema
        Date sistemaFech = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        this.lblFecha.setText(formato.format(sistemaFech));
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.panelVerCliente.setVisible(true);
        this.panelVerConcepto.setVisible(true);
        this.panelBuscarCliente.setVisible(false);
        this.rbMesCorriente.setSelected(true);
        this.rbMesesDeuda.setVisible(false);
        this.rbVariosMeses.setVisible(false);
        JTableHeader th; 
        th = tablaBuscar.getTableHeader(); 
        th.setFont(new java.awt.Font("Eras Medium ITC", 1, 15)); 
        tablaBuscar.setModel(cl.verClientes());
        this.btnVerMeses.setVisible(false);
        if(this.rbMesCorriente.isSelected()){
            this.cbxMeses.addItem(MesCorriente);
        }
        if(cbxConcepto.getSelectedIndex()==0){//Si mensualidad está seleccionada
            this.rbMesCorriente.setVisible(true);
            this.rbMesesDeuda.setVisible(true);
            this.rbVariosMeses.setVisible(true);
            this.lblMes.setVisible(true);
            this.cbxMeses.setVisible(true);
            this.btnVerMeses.setVisible(true);
            this.txtMonto.setText(Float.toString(pg.mensual()));
        }else if(cbxConcepto.getSelectedIndex()==1){//Si inscripción está seleccionado
            this.rbMesCorriente.setVisible(false);
            this.rbMesesDeuda.setVisible(false);
            this.rbVariosMeses.setVisible(false);
            this.lblMes.setVisible(false);
            this.cbxMeses.setVisible(false);
            this.btnVerMeses.setVisible(false);
            this.txtMonto.setText(Float.toString(pg.inscripcion()));
        }
        this.panelDetalles.setVisible(false);
        this.lblNumBoleta.setText(Integer.toString(pg.numPago()));
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        this.panelVerCliente.setVisible(false);
        this.panelBuscarCliente.setVisible(true);
        this.rbNombre.setSelected(true);
        this.rbDpi.setSelected(false);
        this.rbApellido.setSelected(false);
        this.txtBuscarCliente.requestFocus();
        tablaBuscar.setModel(cl.verClientes());
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    
    
    private void rbDpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDpiMouseClicked
        this.rbNombre.setSelected(false);
        this.rbApellido.setSelected(false);
        this.rbDpi.setSelected(true);
        this.txtBuscarCliente.requestFocus();
    }//GEN-LAST:event_rbDpiMouseClicked

    private void rbNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNombreMouseClicked
        this.rbNombre.setSelected(true);
        this.rbApellido.setSelected(false);
        this.rbDpi.setSelected(false);
        this.txtBuscarCliente.requestFocus();
    }//GEN-LAST:event_rbNombreMouseClicked

    //Al hacer click se rellena la información del cliente en el panelVerCliente
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        mostrarCliente();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void mostrarCliente(){
        int filaS = this.tablaBuscar.getSelectedRow();
        if(filaS>=0){
            Object datos[]; 
            datos = new Object[8]; 
            for(int i=0; i<8; i++){
                datos[i] = tablaBuscar.getValueAt(filaS, i);
            }
            this.txtNombres.setText((String) datos[1]);
            this.txtApellidos.setText((String) datos[2]);
            this.txtDpi.setText((String) datos[3]);
            this.txtDireccion.setText((String) datos[4]);
            this.txtMunicipio.setText((String) datos[5]);
            if(datos[6]==null){
                this.txtAldea.setText(" - - - -");
            }else{
             this.txtAldea.setText((String) datos[6]);   
            }
            if(datos[7]==null){
                this.txtCaserio.setText(" - - - -");
            }else{
                this.txtCaserio.setText((String) datos[7]);
            }
            this.panelBuscarCliente.setVisible(false);
            this.panelVerCliente.setVisible(true);
        }else{
            this.panelBuscarCliente.setVisible(false);
            this.panelVerCliente.setVisible(true);
        }
    }
    
    private void panelVerConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVerConceptoMouseClicked
        this.popupMeses.setVisible(false);
    }//GEN-LAST:event_panelVerConceptoMouseClicked

    private void rbApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbApellidoMouseClicked
        this.rbNombre.setSelected(false);
        this.rbApellido.setSelected(true);
        this.rbDpi.setSelected(false);
        this.txtBuscarCliente.requestFocus();
    }//GEN-LAST:event_rbApellidoMouseClicked

    private void txtMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMontoMouseClicked
        this.popupMeses.setVisible(false);
    }//GEN-LAST:event_txtMontoMouseClicked

    private void btnVerMesesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMesesMouseClicked
        if(this.popupMeses.isVisible()==true){
            this.popupMeses.setVisible(false);
        }else{
            this.popupMeses.setLocation(evt.getLocationOnScreen());
            this.popupMeses.setVisible(true);
        }
    }//GEN-LAST:event_btnVerMesesMouseClicked

    private void cbxEneroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEneroItemStateChanged
        itemsMeses(cbxEnero);
    }//GEN-LAST:event_cbxEneroItemStateChanged

    private void cbxFebreroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFebreroItemStateChanged
        itemsMeses(cbxFebrero);
    }//GEN-LAST:event_cbxFebreroItemStateChanged

    private void cbxMarzoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMarzoItemStateChanged
        itemsMeses(cbxMarzo);
    }//GEN-LAST:event_cbxMarzoItemStateChanged

    private void cbxAbrilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAbrilItemStateChanged
        itemsMeses(cbxAbril);
    }//GEN-LAST:event_cbxAbrilItemStateChanged

    private void cbxMayoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMayoItemStateChanged
        itemsMeses(cbxMayo);
    }//GEN-LAST:event_cbxMayoItemStateChanged

    private void cbxJunioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxJunioItemStateChanged
        itemsMeses(cbxJunio);
    }//GEN-LAST:event_cbxJunioItemStateChanged

    private void cbxJulioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxJulioItemStateChanged
        itemsMeses(cbxJulio);
    }//GEN-LAST:event_cbxJulioItemStateChanged

    private void cbxAgostoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAgostoItemStateChanged
        itemsMeses(cbxAgosto);
    }//GEN-LAST:event_cbxAgostoItemStateChanged

    private void cbxSeptiembreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSeptiembreItemStateChanged
        itemsMeses(cbxSeptiembre);
    }//GEN-LAST:event_cbxSeptiembreItemStateChanged

    private void cbxOctubreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxOctubreItemStateChanged
        itemsMeses(cbxOctubre);
    }//GEN-LAST:event_cbxOctubreItemStateChanged

    private void cbxNoviembreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNoviembreItemStateChanged
        itemsMeses(cbxNoviembre);
    }//GEN-LAST:event_cbxNoviembreItemStateChanged

    private void cbxDiciembreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDiciembreItemStateChanged
        itemsMeses(cbxDiciembre);
    }//GEN-LAST:event_cbxDiciembreItemStateChanged

    private void rbVariosMesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbVariosMesesItemStateChanged
        if(rbVariosMeses.isSelected()==true){
            this.rbMesCorriente.setSelected(false);
            this.rbMesesDeuda.setSelected(false);
            this.btnVerMeses.setVisible(true);
        }
    }//GEN-LAST:event_rbVariosMesesItemStateChanged

    private void rbMesesDeudaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbMesesDeudaItemStateChanged
        
    }//GEN-LAST:event_rbMesesDeudaItemStateChanged

    private void cbxConceptoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxConceptoItemStateChanged
        if(cbxConcepto.getSelectedIndex()==0){//Si mensualidad está seleccionada
            this.rbMesCorriente.setVisible(true);
            this.rbMesesDeuda.setVisible(true);
            this.rbVariosMeses.setVisible(true);
            this.lblMes.setVisible(true);
            this.cbxMeses.setVisible(true);
            this.btnVerMeses.setVisible(true);
            this.txtMonto.setText(Float.toString(pg.mensual()));
        }else if(cbxConcepto.getSelectedIndex()==1){//Si inscripción está seleccionado
            this.rbMesCorriente.setVisible(false);
            this.rbMesesDeuda.setVisible(false);
            this.rbVariosMeses.setVisible(false);
            this.lblMes.setVisible(false);
            this.cbxMeses.setVisible(false);
            this.btnVerMeses.setVisible(false);
            this.txtMonto.setText(Float.toString(pg.inscripcion()));
        }
    }//GEN-LAST:event_cbxConceptoItemStateChanged

    private void filler2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filler2MouseClicked
        this.popupMeses.setVisible(false);
    }//GEN-LAST:event_filler2MouseClicked

    private void txtBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyReleased
        String cadBuscar;
        cadBuscar = this.txtBuscarCliente.getText();
        if(cadBuscar.isEmpty()){
            cl.limpiarTabla();
            tablaBuscar.setModel(cl.verClientes());
        }else{
            cl.limpiarTabla();
            if(rbDpi.isSelected()==true){//Buscar por dpi
                tablaBuscar.setModel(cl.verCDpi(cadBuscar));
            }else if(rbNombre.isSelected()==true){//Buscar por nombre
                tablaBuscar.setModel(cl.verCNombre(cadBuscar));
            }else{//Buscar por apellido
                tablaBuscar.setModel(cl.verCApellido(cadBuscar));
            }
        }
    }//GEN-LAST:event_txtBuscarClienteKeyReleased

    private void tablaBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBuscarMouseClicked
        if(evt.getClickCount()==2){//Si se hace doble click
            mostrarCliente();
        }
    }//GEN-LAST:event_tablaBuscarMouseClicked

    private void rbVariosMesesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbVariosMesesMouseClicked
        this.cbxMeses.removeItem(formato2.format(sistemaFech2).toUpperCase());
        this.rbVariosMeses.setSelected(true);
        this.rbMesCorriente.setSelected(false);
        this.rbMesesDeuda.setSelected(false);
        this.btnVerMeses.setVisible(true);
    }//GEN-LAST:event_rbVariosMesesMouseClicked

    private void rbMesCorrienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMesCorrienteMouseClicked
        this.rbMesCorriente.setSelected(true);
        this.rbVariosMeses.setSelected(false);
        this.rbMesesDeuda.setSelected(false);    
        this.cbxMeses.addItem(MesCorriente);
        this.btnVerMeses.setVisible(false);
        
    }//GEN-LAST:event_rbMesCorrienteMouseClicked

    private void rbMesesDeudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMesesDeudaMouseClicked
        this.cbxMeses.removeItem(MesCorriente);
        this.rbMesesDeuda.setSelected(true);
        this.rbMesCorriente.setSelected(false);
        this.rbVariosMeses.setSelected(false);
        this.btnVerMeses.setVisible(false);
    }//GEN-LAST:event_rbMesesDeudaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Desea cancelar los cambios?", "Cerrar", JOptionPane.YES_NO_OPTION, 0,
            new ImageIcon(getClass().getResource("/Imagenes/modificar.png"))) == JOptionPane.YES_OPTION) {
            //Registrar pago
            Date sistemaHora = new Date();
            String pmAm = "hh:mm a";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            String hora= (String.format(formato.format(sistemaHora), now));
            if(cbxConcepto.getSelectedIndex()==0){
                pg.pagarIns(Integer.toString(pg.numPago()+1), "A", Integer.toString(pg.numPago()+1),"Pago Mensual" , 
                        MesCorriente, this.lblFecha.getText(), hora, "1", Integer.toString(pg.idCli(this.txtDpi.getText())));
            }
            if(cbxConcepto.getSelectedIndex()==1){
                pg.pagarIns(Integer.toString(pg.numPago()+1), "A", Integer.toString(pg.numPago()+1),"Inscripción" , 
                        MesCorriente, this.lblFecha.getText(), hora, "2", Integer.toString(pg.idCli(this.txtDpi.getText())));
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemsMeses(JCheckBoxMenuItem cbx){
        if(cbx.getState()==true){
            this.cbxMeses.addItem(cbx.getText());
        }else{
            this.cbxMeses.removeItem(cbx.getText());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Monto;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnVerMeses;
    private javax.swing.JCheckBoxMenuItem cbxAbril;
    private javax.swing.JCheckBoxMenuItem cbxAgosto;
    public static javax.swing.JComboBox<String> cbxConcepto;
    private javax.swing.JCheckBoxMenuItem cbxDiciembre;
    private javax.swing.JCheckBoxMenuItem cbxEnero;
    private javax.swing.JCheckBoxMenuItem cbxFebrero;
    private javax.swing.JCheckBoxMenuItem cbxJulio;
    private javax.swing.JCheckBoxMenuItem cbxJunio;
    private javax.swing.JCheckBoxMenuItem cbxMarzo;
    private javax.swing.JCheckBoxMenuItem cbxMayo;
    public static javax.swing.JComboBox<String> cbxMeses;
    private javax.swing.JCheckBoxMenuItem cbxNoviembre;
    private javax.swing.JCheckBoxMenuItem cbxOctubre;
    private javax.swing.JCheckBoxMenuItem cbxSeptiembre;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAldea;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCaserio;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDpi;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNombres;
    public static javax.swing.JLabel lblNumBoleta;
    private javax.swing.JPanel panelBoleta;
    private javax.swing.JPanel panelBuscarCliente;
    private javax.swing.JLayeredPane panelCliente;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JPanel panelFechaEm;
    private javax.swing.JPanel panelPrin;
    private javax.swing.JPanel panelVerCliente;
    private javax.swing.JPanel panelVerConcepto;
    private javax.swing.JPopupMenu popupMeses;
    private javax.swing.JRadioButton rbApellido;
    private javax.swing.JRadioButton rbDpi;
    private javax.swing.JRadioButton rbMesCorriente;
    private javax.swing.JRadioButton rbMesesDeuda;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JRadioButton rbVariosMeses;
    private javax.swing.JTable tablaBuscar;
    private javax.swing.JTable tblComprobante;
    private javax.swing.JTextField txtAldea;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtCaserio;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDpi;
    public static javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
