package Interfaz;

import ConexionBaseDatos.Conexion;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Principal extends javax.swing.JFrame {
    Conexion conn = new Conexion();
    Connection con;
    Pago pago = new Pago();
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.escritorio.add(pago);
        btnPagos.setSize(170, 110);
        btnEmpleados.setSize(170, 110);
        btnTraslados.setSize(170, 110);
        btnInventario.setSize(170, 110);
        btnVehiculos.setSize(170, 110);
        panelOpciones1.setSize(170,110);
        ImageIcon imagen[] = new ImageIcon[5];
        imagen[0] = new ImageIcon("src/Imagenes/05.icono_btn_pagos.png");
        imagen[1] = new ImageIcon("src/Imagenes/06.icono_btn_empleados.png");
        imagen[2] = new ImageIcon("src/Imagenes/07.icono_btn_traslados.png");
        imagen[3] = new ImageIcon("src/Imagenes/08.icono_btn_inventario.png");
        imagen[4] = new ImageIcon("src/Imagenes/09.icono_btn_vehiculos.png");
        escalarImagen(btnPagos, imagen[0]);
        escalarImagen(btnEmpleados, imagen[1]);
        escalarImagen(btnTraslados, imagen[2]);
        escalarImagen(btnInventario, imagen[3]);
        escalarImagen(btnVehiculos, imagen[4]);
        //int ancho = this.panelSuperior.getWidth();
        //int alto = this.panelSuperior.getHeight();
        //ancho = (ancho*20)/100;
        //this.panelOpciones1.setSize(ancho, alto);
    }

    private void escalarImagen(JButton btn, ImageIcon img){
        //se recibe la imagen en un Image
        Image imagen = img.getImage();
        //ahora se realiza la parte principal de este video que es adaptar el tamaño de la imagen a nuestro label
        Image nuevaimagen = imagen.getScaledInstance(btn.getWidth(), btn.getHeight(), Image.SCALE_SMOOTH);
        //finalmente le adicinamos la imagen dentro del label
        btn.setIcon(new ImageIcon(nuevaimagen));
    }
    
    //Funcion para escalar imagen reduciendo un 5%
    private void escalarImagen2(JButton btn, ImageIcon img){
        //se recibe la imagen en un Image
        Image imagen = img.getImage();
        int ancho = btn.getWidth();
        int alto = btn.getHeight();
        ancho = (ancho*95)/100;
        alto = (alto*95)/100;
        //ahora se realiza la parte principal de este video que es adaptar el tamaño de la imagen a nuestro label
        Image nuevaimagen = imagen.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        //finalmente le adicinamos la imagen dentro del label
        btn.setIcon(new ImageIcon(nuevaimagen));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        panelOpciones1 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        iconoUsuario = new javax.swing.JLabel();
        iconoCerrar = new javax.swing.JLabel();
        panelOpciones2 = new javax.swing.JPanel();
        btnPagos = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnTraslados = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tren de Aseo");
        setBackground(new java.awt.Color(0, 102, 0));
        setName("framePrincipal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelSuperior.setBackground(new java.awt.Color(71, 80, 98));
        panelSuperior.setLayout(new java.awt.BorderLayout());

        panelOpciones1.setBackground(new java.awt.Color(71, 80, 98));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("FECHA");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuario.setText("Usuario: ");

        lblHora.setBackground(new java.awt.Color(255, 255, 255));
        lblHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("HORA");

        lblCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCerrarSesion.setText("Cerrar Sesión");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        iconoUsuario.setBackground(new java.awt.Color(0, 153, 153));
        iconoUsuario.setOpaque(true);

        iconoCerrar.setBackground(new java.awt.Color(0, 153, 153));
        iconoCerrar.setOpaque(true);
        iconoCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOpciones1Layout = new javax.swing.GroupLayout(panelOpciones1);
        panelOpciones1.setLayout(panelOpciones1Layout);
        panelOpciones1Layout.setHorizontalGroup(
            panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpciones1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpciones1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(iconoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addGroup(panelOpciones1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconoCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        panelOpciones1Layout.setVerticalGroup(
            panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpciones1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpciones1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(iconoCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOpciones1Layout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGap(20, 20, 20))
        );

        panelSuperior.add(panelOpciones1, java.awt.BorderLayout.WEST);

        panelOpciones2.setBackground(new java.awt.Color(71, 80, 98));
        panelOpciones2.setLayout(new java.awt.GridLayout(1, 5));

        btnPagos.setBackground(new java.awt.Color(54, 68, 97));
        btnPagos.setBorder(null);
        btnPagos.setBorderPainted(false);
        btnPagos.setContentAreaFilled(false);
        btnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagos.setFocusPainted(false);
        btnPagos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagos.setMaximumSize(new java.awt.Dimension(70, 70));
        btnPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPagosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPagosMouseReleased(evt);
            }
        });
        btnPagos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnPagosComponentResized(evt);
            }
        });
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        panelOpciones2.add(btnPagos);

        btnEmpleados.setBackground(new java.awt.Color(54, 68, 97));
        btnEmpleados.setBorder(null);
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.setFocusPainted(false);
        btnEmpleados.setMaximumSize(new java.awt.Dimension(70, 70));
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpleadosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseReleased(evt);
            }
        });
        btnEmpleados.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnEmpleadosComponentResized(evt);
            }
        });
        panelOpciones2.add(btnEmpleados);

        btnTraslados.setBackground(new java.awt.Color(54, 68, 97));
        btnTraslados.setBorder(null);
        btnTraslados.setBorderPainted(false);
        btnTraslados.setContentAreaFilled(false);
        btnTraslados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTraslados.setFocusPainted(false);
        btnTraslados.setMaximumSize(new java.awt.Dimension(70, 70));
        btnTraslados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrasladosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrasladosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrasladosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTrasladosMouseReleased(evt);
            }
        });
        btnTraslados.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnTrasladosComponentResized(evt);
            }
        });
        panelOpciones2.add(btnTraslados);

        btnInventario.setBackground(new java.awt.Color(54, 68, 97));
        btnInventario.setBorder(null);
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.setFocusPainted(false);
        btnInventario.setMaximumSize(new java.awt.Dimension(70, 70));
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInventarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInventarioMouseReleased(evt);
            }
        });
        btnInventario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnInventarioComponentResized(evt);
            }
        });
        panelOpciones2.add(btnInventario);

        btnVehiculos.setBackground(new java.awt.Color(54, 68, 97));
        btnVehiculos.setBorder(null);
        btnVehiculos.setBorderPainted(false);
        btnVehiculos.setContentAreaFilled(false);
        btnVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVehiculos.setFocusPainted(false);
        btnVehiculos.setMaximumSize(new java.awt.Dimension(70, 70));
        btnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVehiculosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseReleased(evt);
            }
        });
        btnVehiculos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnVehiculosComponentResized(evt);
            }
        });
        panelOpciones2.add(btnVehiculos);

        panelSuperior.add(panelOpciones2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelContenido.setBackground(new java.awt.Color(48, 57, 74));

        escritorio.setBackground(new java.awt.Color(71, 80, 98));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(escritorio)
                .addGap(20, 20, 20))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(escritorio)
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarInternal(JInternalFrame internal){
        internal.setVisible(true);
        try {  
            internal.setMaximum(true);
        }catch(PropertyVetoException e) {}
        internal.show();
    }
    
    private void btnPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMouseEntered
        escalarImagen2(btnPagos,new ImageIcon("src/Imagenes/05.icono_btn_pagos.png"));
    }//GEN-LAST:event_btnPagosMouseEntered

    private void btnPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMouseExited
        escalarImagen(btnPagos,new ImageIcon("src/Imagenes/05.icono_btn_pagos.png"));
    }//GEN-LAST:event_btnPagosMouseExited

    private void btnPagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMousePressed
        this.btnPagos.setOpaque(true);
    }//GEN-LAST:event_btnPagosMousePressed

    private void btnPagosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMouseReleased
        this.btnPagos.setOpaque(false);
    }//GEN-LAST:event_btnPagosMouseReleased

    private void btnPagosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnPagosComponentResized
        escalarImagen(btnPagos,new ImageIcon("src/Imagenes/05.icono_btn_pagos.png"));
    }//GEN-LAST:event_btnPagosComponentResized

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        //this.panelMenu.setVisible(false);
        this.mostrarInternal(pago);
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseEntered
        escalarImagen2(btnEmpleados,new ImageIcon("src/Imagenes/06.icono_btn_empleados.png"));
    }//GEN-LAST:event_btnEmpleadosMouseEntered

    private void btnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseExited
        escalarImagen(btnEmpleados,new ImageIcon("src/Imagenes/06.icono_btn_empleados.png"));
    }//GEN-LAST:event_btnEmpleadosMouseExited

    private void btnEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMousePressed
        this.btnEmpleados.setOpaque(true);
    }//GEN-LAST:event_btnEmpleadosMousePressed

    private void btnEmpleadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseReleased
        this.btnEmpleados.setOpaque(false);
    }//GEN-LAST:event_btnEmpleadosMouseReleased

    private void btnEmpleadosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnEmpleadosComponentResized
        escalarImagen(btnEmpleados,new ImageIcon("src/Imagenes/06.icono_btn_empleados.png"));
    }//GEN-LAST:event_btnEmpleadosComponentResized

    private void btnTrasladosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrasladosMouseEntered
        escalarImagen2(btnTraslados,new ImageIcon("src/Imagenes/07.icono_btn_traslados.png"));
    }//GEN-LAST:event_btnTrasladosMouseEntered

    private void btnTrasladosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrasladosMouseExited
        escalarImagen(btnTraslados,new ImageIcon("src/Imagenes/07.icono_btn_traslados.png"));
    }//GEN-LAST:event_btnTrasladosMouseExited

    private void btnTrasladosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrasladosMousePressed
        this.btnTraslados.setOpaque(true);
    }//GEN-LAST:event_btnTrasladosMousePressed

    private void btnTrasladosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrasladosMouseReleased
        this.btnTraslados.setOpaque(false);
    }//GEN-LAST:event_btnTrasladosMouseReleased

    private void btnTrasladosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnTrasladosComponentResized
        escalarImagen(btnTraslados,new ImageIcon("src/Imagenes/07.icono_btn_traslados.png"));
    }//GEN-LAST:event_btnTrasladosComponentResized

    private void btnInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseEntered
        escalarImagen2(btnInventario,new ImageIcon("src/Imagenes/08.icono_btn_inventario.png"));
    }//GEN-LAST:event_btnInventarioMouseEntered

    private void btnInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseExited
        escalarImagen(btnInventario,new ImageIcon("src/Imagenes/08.icono_btn_inventario.png"));
    }//GEN-LAST:event_btnInventarioMouseExited

    private void btnInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMousePressed
        this.btnInventario.setOpaque(true);
    }//GEN-LAST:event_btnInventarioMousePressed

    private void btnInventarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseReleased
        this.btnInventario.setOpaque(false);
    }//GEN-LAST:event_btnInventarioMouseReleased

    private void btnInventarioComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnInventarioComponentResized
        escalarImagen(btnInventario,new ImageIcon("src/Imagenes/08.icono_btn_inventario.png"));
    }//GEN-LAST:event_btnInventarioComponentResized

    private void btnVehiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseEntered
        escalarImagen2(btnVehiculos,new ImageIcon("src/Imagenes/09.icono_btn_vehiculos.png"));
    }//GEN-LAST:event_btnVehiculosMouseEntered

    private void btnVehiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseExited
        escalarImagen(btnVehiculos,new ImageIcon("src/Imagenes/09.icono_btn_vehiculos.png"));
    }//GEN-LAST:event_btnVehiculosMouseExited

    private void btnVehiculosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMousePressed
        this.btnVehiculos.setOpaque(true);
    }//GEN-LAST:event_btnVehiculosMousePressed

    private void btnVehiculosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseReleased
        this.btnVehiculos.setOpaque(false);
    }//GEN-LAST:event_btnVehiculosMouseReleased

    private void btnVehiculosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnVehiculosComponentResized
        escalarImagen(btnVehiculos,new ImageIcon("src/Imagenes/09.icono_btn_vehiculos.png"));
    }//GEN-LAST:event_btnVehiculosComponentResized

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, "Salir de la Aplicación.\n¿Desea continuar?", "Cerrar", JOptionPane.YES_NO_OPTION, 0,
                new ImageIcon(getClass().getResource("/Imagenes/btnSalir.png"))) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }else{
            this.setDefaultCloseOperation(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Fehca del sistema
        Date sistemaFech = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd MMMM yyyy");
        this.lblFecha.setText(formato.format(sistemaFech));

        //Hora del sistema
        Timer tiempo = new Timer(100, new Principal.horas());
        tiempo.start();
    }//GEN-LAST:event_formWindowOpened

    private void iconoCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCerrarMouseClicked
        cerrarSesion();
    }//GEN-LAST:event_iconoCerrarMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        cerrarSesion();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked
   
    private void cerrarSesion(){
        if (JOptionPane.showConfirmDialog(this, "Desea cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION, 0,
                new ImageIcon(getClass().getResource("/Imagenes/btnCerrarSesion.png"))) == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login().setVisible(true);
        }
    }
    
    class horas implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Date sistemaHora = new Date();
            String pmAm = "hh:mm a";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format(formato.format(sistemaHora), now));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnTraslados;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel iconoCerrar;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelOpciones1;
    private javax.swing.JPanel panelOpciones2;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
